# Generated by Django 4.0.6 on 2022-07-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='fullname',
            field=models.CharField(help_text='Введите имя и фамилию докладчика', max_length=100, verbose_name='Имя и фамилия выступающего'),
        ),
    ]
